name: AWS repo Sync

on:
  workflow_dispatch:

jobs:
  clone_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Sparse checkout
        uses: actions/checkout@v4
        with:
          repository: 'aws-actions/vulnerability-scan-github-action-for-amazon-inspector'
          sparse-checkout: |
            *
            !.github/
